### ISSUE TITLE
Add docker for Python Section

### ISSUE THREAD

**Issue by bhavaniravi** [docker/get-involved#38]
It looks like Docker for Python developers would be a nice section to add. We can also extend it to dockerizing ML apps. I have worked on both, would be happy to contribute.

**Comment by ajeetraina** [comment]
@bhavaniravi Would you be interested to contribute? Go ahead and raise PR.

**Comment by bhavaniravi** [comment]
Yes, I am. Let me start this

**Comment by ajeetraina** [comment]
Thanks @bhavaniravi for contributing Python tutorial.
