### ISSUE TITLE
Add the right thumbnail for .NET developers

### ISSUE THREAD

**Issue by ajeetraina** [docker/get-involved#57]
The https://contribute.docker.com/docs/communityleaders/eventhandbooks/ page needs improvement in terms of .NET thumbnail. Right now, it just shows Docker thumbnail but it needs to be .NET related thumbnail.

**Comment by ajeetraina** [comment]
@zhangxd6 Would you like to work on this?

**Comment by zhangxd6** [comment]
sure

**Comment by zhangxd6** [comment]
[PR#62](https://github.com/docker/get-involved/pull/62)
